version: "3.9"

services:
  tf-jupyter:
    build: .
    container_name: tf-gpu-jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./Notebooks:/tf
    working_dir: /tf
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: >
      bash -c "jupyter notebook
      --ip=0.0.0.0
      --no-browser
      --allow-root
      --NotebookApp.token=''
      --NotebookApp.password=''"
