version: "3.9"

services:
  tf-jupyter:
    build: .
    container_name: tf-gpu-jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ./Notebooks:/tf
    working_dir: /tf
   # Si es que no esta conectado a una GPU o si la portatil no esta conectada a la corriente, comentar las siguientes lineas
    deploy:
       resources:
         reservations:
           devices:
             - capabilities: [gpu]
    command: >
      bash -c "jupyter notebook
      --ip=0.0.0.0
      --no-browser
      --allow-root
      --NotebookApp.token=''
      --NotebookApp.password=''"
